In [4]:

import numpy as np

ratings=np.array([[5,4],[2,3],[7,8],[10,19]])
print(ratings)

[[ 5  4]
 [ 2  3]
 [ 7  8]
 [10 19]]


In [6]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.random.rand(5)

array([0.27341745, 0.08886629, 0.5418703 , 0.93120437, 0.98476598])

In [17]:
rng=np.random.default_rng()
mat=rng.integers(low=0,high=100,size=(3,3))
print(mat)

[[76 10 24]
 [70 71 48]
 [ 6  3 11]]


In [22]:
a=np.arange(0,9)
a.reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
a=np.random.rand(15)
a

array([0.96407867, 0.90861454, 0.31602364, 0.10181842, 0.99160715,
       0.71343818, 0.11335858, 0.56206602, 0.34356384, 0.75907005,
       0.92679198, 0.67731857, 0.78792707, 0.76069774, 0.41988176])

In [28]:
result=np.linspace(1,2,num=5)  # produce evenly spaced number
print(result)

[1.   1.25 1.5  1.75 2.  ]


In [29]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [38]:
b=np.arange(0,16)


In [39]:
b.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [53]:
arr[1,1]

np.int64(5)

In [54]:
arr[1:,1]

array([ 5,  8, 11])

In [55]:
# array[row_start:row_stop:row_step, col_start:col_stop:col_step]
arr[0:2,1:]

array([[2, 3],
       [5, 6]])

In [57]:
print(np.sum(arr))

78


In [58]:
# SVD

from scipy.linalg import svd
matrix=np.arange(1,19).reshape(6,3)

In [59]:
U,s,VT=svd(matrix)
U

array([[-0.07736219,  0.71960032, -0.09075777, -0.25083666, -0.45979172,
        -0.4400296 ],
       [-0.19033085,  0.50893247,  0.58409372,  0.4022013 ,  0.06897105,
         0.44392965],
       [-0.3032995 ,  0.29826463, -0.34118019, -0.54123699,  0.50890998,
         0.38822268],
       [-0.41626816,  0.08759679, -0.61888418,  0.65636038,  0.03282454,
        -0.06437079],
       [-0.52923682, -0.12307105,  0.37872289, -0.04363171,  0.43069535,
        -0.61149707],
       [-0.64220548, -0.33373889,  0.08800553, -0.22285632, -0.58160921,
         0.28374512]])

In [60]:
s

array([4.58945322e+01, 1.64070530e+00, 1.74146424e-15])

In [61]:
VT

array([[-0.52903535, -0.57607152, -0.62310769],
       [-0.74394551, -0.03840487,  0.66713577],
       [ 0.40824829, -0.81649658,  0.40824829]])

In [65]:
U,s,VT=svd(matrix,full_matrices=True)
U

array([[-0.07736219,  0.71960032, -0.09075777, -0.25083666, -0.45979172,
        -0.4400296 ],
       [-0.19033085,  0.50893247,  0.58409372,  0.4022013 ,  0.06897105,
         0.44392965],
       [-0.3032995 ,  0.29826463, -0.34118019, -0.54123699,  0.50890998,
         0.38822268],
       [-0.41626816,  0.08759679, -0.61888418,  0.65636038,  0.03282454,
        -0.06437079],
       [-0.52923682, -0.12307105,  0.37872289, -0.04363171,  0.43069535,
        -0.61149707],
       [-0.64220548, -0.33373889,  0.08800553, -0.22285632, -0.58160921,
         0.28374512]])

In [67]:
U,s,VT=svd(matrix,full_matrices=False)
U

array([[-0.07736219,  0.71960032, -0.09075777],
       [-0.19033085,  0.50893247,  0.58409372],
       [-0.3032995 ,  0.29826463, -0.34118019],
       [-0.41626816,  0.08759679, -0.61888418],
       [-0.52923682, -0.12307105,  0.37872289],
       [-0.64220548, -0.33373889,  0.08800553]])

In [68]:
from numpy import diag
from numpy import dot
matrix=(U@np.diag(s)@VT)
matrix

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.]])